stages:
    - build
    - qa
    - test

variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

cache:
    key:
        files:
            - composer.lock
    paths:
        - .composer-cache/
        - vendor/

image:
    name: $CI_REGISTRY_IMAGE/php:latest
    pull_policy: always

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build -t $CI_REGISTRY_IMAGE/php:latest -f docker/frankenphp/Dockerfile --target frankenphp_dev .
        - docker push $CI_REGISTRY_IMAGE/php:latest

.php_base:
    needs:
        - job: build
          optional: true
    before_script:
        - composer install --no-interaction --prefer-dist --optimize-autoloader

cs-fixer:
    extends: .php_base
    stage: qa
    script:
        - composer qa:cs-fix

rector:
    extends: .php_base
    stage: qa
    script:
        - composer qa:rector

phpstan:
    extends: .php_base
    stage: qa
    script:
        - composer qa:phpstan

phpunit:
    extends: .php_base
    stage: test
    services:
        - name: postgres:18
          alias: database
    variables:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
    before_script:
        - echo 'DATABASE_URL=postgresql://test:test@database:5432/test?serverVersion=18&charset=utf8' >> .env.test
    script:
        - composer qa:phpunit

twig-fixer:
    extends: .php_base
    stage: qa
    script:
        - composer qa:twig-fix
