stages:
    - build
    - qa
    - test

variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

cache:
    key:
        files:
            - composer.lock
    paths:
        - .composer-cache/
        - vendor/

image:
    name: $CI_REGISTRY_IMAGE/php:latest
    pull_policy: always

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build -t $CI_REGISTRY_IMAGE/php:latest -f docker/php/Dockerfile .
        - docker push $CI_REGISTRY_IMAGE/php:latest

.php_base:
    needs:
        - job: build
          optional: true
    before_script:
        - composer install --no-interaction --prefer-dist --optimize-autoloader

cs-fixer:
    extends: .php_base
    stage: qa
    script:
        - composer qa:cs-fix

rector:
    extends: .php_base
    stage: qa
    script:
        - composer qa:rector

phpstan:
    extends: .php_base
    stage: qa
    script:
        - composer qa:phpstan

phpunit:
    extends: .php_base
    stage: test
    services:
        - name: mysql:8.4
          alias: database
    variables:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: root
    before_script:
        - echo 'DATABASE_URL=mysql://root:root@mysql:3306/test?serverVersion=8.4.3&charset=utf8mb4' >> .env.test
    script:
        - composer qa:phpunit

twig-fixer:
    extends: .php_base
    stage: qa
    script:
        - composer qa:twig-fix
