image:
  name: thecodingmachine/php:8.5-v5-cli
  run-as-user: 0

definitions:
  services:
    postgres:
      image: postgres:18
      variables:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test

  caches:
    composer: .composer-cache
    vendor: vendor

  steps:
    - step: &cs-fixer
        name: CS Fixer
        caches:
          - composer
          - vendor
        script:
          - &setup |
            set -e
            PHP_EXTENSION_INTL=1 PHP_EXTENSION_GD=1 PHP_EXTENSION_PDO_PGSQL=1 PHP_EXTENSION_PCOV=1 php /usr/local/bin/setup_extensions.php
            export COMPOSER_CACHE_DIR="$BITBUCKET_CLONE_DIR/.composer-cache"
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-interaction --prefer-dist --optimize-autoloader
          - composer qa:cs-fix

    - step: &rector
        name: Rector
        caches:
          - composer
          - vendor
        script:
          - *setup
          - composer qa:rector

    - step: &phpstan
        name: PHPStan
        caches:
          - composer
          - vendor
        script:
          - *setup
          - composer qa:phpstan

    - step: &twig-fixer
        name: Twig Fixer
        caches:
          - composer
          - vendor
        script:
          - *setup
          - composer qa:twig-fix

    - step: &phpunit
        name: PHPUnit
        services:
          - postgres
        caches:
          - composer
          - vendor
        script:
          - *setup
          - echo 'DATABASE_URL=postgresql://test:test@127.0.0.1:5432/test?serverVersion=18&charset=utf8' >> .env.test
          - php bin/phpunit

pipelines:
  default:
    - parallel:
        - step: *cs-fixer
        - step: *rector
        - step: *phpstan
        - step: *twig-fixer
    - step: *phpunit

  pull-requests:
    '**':
      - parallel:
          - step: *cs-fixer
          - step: *rector
          - step: *phpstan
          - step: *twig-fixer
      - step: *phpunit

  branches:
    main:
      - parallel:
          - step: *cs-fixer
          - step: *rector
          - step: *phpstan
          - step: *twig-fixer
      - step: *phpunit
