name: CI Pipeline

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    extensions: apcu, intl, opcache, pdo, pdo_mysql, pcov, redis, zip
                    php-version: 8.3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_extensions: redis
                    php_version: 8.3
            -   name: Wait for MySQL to be ready
                run: |
                    for i in {1..10}; do
                      if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
                        echo "MySQL is ready!";
                        break;
                      fi
                      echo "Waiting for MySQL to be ready...";
                      sleep 3;
                    done
            -   name: Test MySQL Connection
                run: mysql -h127.0.0.1 -uroot -proot -e "SHOW DATABASES;"
            -   name: Run PHPStan
                run: vendor/bin/phpstan --memory-limit=1G
            -   name: Run PHPUnit
                run: vendor/bin/phpunit
                env:
                    DATABASE_URL: "mysql://root:root@127.0.0.1:3306/test?serverVersion=8.0.32&charset=utf8mb4"
