name: CI Pipeline

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    extensions: apcu, intl, opcache, pdo, pdo_mysql, pcov, redis, zip
                    php-version: 8.3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_extensions: redis
                    php_version: 8.3
    phpunit:
        needs: build
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Run PHPUnit
                run: vendor/bin/phpunit --coverage-text
    phpstan:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Run PHPStan
                run: vendor/bin/phpstan --memory-limit=1G
