name: CI Pipeline

on:
    - push

jobs:
    setup:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.4.3
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    extensions: apcu, intl, opcache, pdo, pdo_mysql, pcov, redis, zip
                    php-version: 8.3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_extensions: redis
                    php_version: 8.3
    rector:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Run Rector
                run: vendor/bin/rector --dry-run --no-progress-bar
    php-cs-fixer:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Run PHP-CS-Fixer
                run: vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --show-progress=none
    twig-cs-fixer:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Run Twig-CS-Fixer
                run: vendor/bin/twig-cs-fixer lint templates
    phpstan:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Dump cache
                run: bin/console cache:clear --env=dev
            -   name: Run PHPStan
                run: vendor/bin/phpstan --memory-limit=1G --no-progress
    phpunit:
        needs: setup
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.4.3
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: pcov
                    extensions: apcu, intl, opcache, pdo, pdo_mysql, pcov, redis, zip
                    php-version: 8.3
            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Run PHPUnit
                run: vendor/bin/phpunit --coverage-text
                env:
                    DATABASE_URL: "mysql://root:root@127.0.0.1:3306/test?serverVersion=8.4.3&charset=utf8mb4"
